if(typeof(ga)=='undefined'||!ga){}
var play_time=0;function timerTracking()
{ga('send','pageview');ga('hayhaytvold.send','pageview');t=setTimeout("timerTracking()",240000);}
function eventTracking(name,action,description)
{play_time+=30;ga('send','event',name,action,description);t=setTimeout(function(){eventTracking(name,action,"Đã xem "+play_time+"m")},1800000);}
function ga_event(name,action,description,value,implicit_count){if(typeof(value)!='undefined'&&value){if(typeof(implicit_count)!='undefined'&&implicit_count){ga('send','event',name,action,description,value,implicit_count);ga('hayhaytvold.send','event',name,action,description,value,implicit_count);}else{ga('send','event',name,action,description,value);ga('hayhaytvold.send','event',name,action,description,value);}}else{ga('send','event',name,action,description);ga('hayhaytvold.send','event',name,action,description);}}
function ga_event_ads(name,action,description,value,implicit_count){if(typeof(value)!='undefined'&&value){if(typeof(implicit_count)!='undefined'&&implicit_count){ga('ads.send','event',name,action,description,value,implicit_count);}else{ga('ads.send','event',name,action,description,value);}}else{ga('ads.send','event',name,action,description,{nonInteraction:true});}}
function ga_event_play(name,action,description,value,implicit_count){if(typeof(value)!='undefined'&&value){if(typeof(implicit_count)!='undefined'&&implicit_count){ga('play.send','event',name,action,description,value,implicit_count);}else{ga('play.send','event',name,action,description,value);}}else{ga('play.send','event',name,action,description,{nonInteraction:true});}}
function ga_event_banner(name,action,description,value,implicit_count){if(typeof(value)!='undefined'&&value){if(typeof(implicit_count)!='undefined'&&implicit_count){ga('banner.send','event',name,action,description,value,implicit_count);}else{ga('banner.send','event',name,action,description,value);}}else{ga('banner.send','event',name,action,description,{nonInteraction:true});}}
function ga_payment(category,action,label,value,code,transaction){ga('require','ecommerce');ga_event(category,action,label,value);transaction+=code;ga('ecommerce:addTransaction',{'id':transaction,'affiliation':category,'revenue':value,'shipping':'0','tax':'0'});ga('ecommerce:addItem',{'id':transaction,'name':label,'sku':code,'category':category,'price':value,'quantity':'1'});ga('ecommerce:send')}
function ga_event(name,action,description,value,implicit_count){if(typeof(value)!='undefined'&&value){if(typeof(implicit_count)!='undefined'&&implicit_count){ga('send','event',name,action,description,value,implicit_count);ga('hayhaytvold.send','event',name,action,description,value,implicit_count);}else{ga('send','event',name,action,description,value);ga('hayhaytvold.send','event',name,action,description,value);}}else{ga('send','event',name,action,description);ga('hayhaytvold.send','event',name,action,description);}}
var URL_API_AT="http://at.hayhaytv.vn/";function api_impression_hit(id_campaign,id_partner){var url_api_impression=URL_API_AT+"api/impression_hit";return $.ajax({url:url_api_impression,data:"id_campaign="+ id_campaign+"&id_partner="+ id_partner,type:"GET",dataType:"jsonp",crossDomain:true,jsonp:"impression",jsonpCallback:"jsonp_call_result_impression"});}
function jsonp_call_result_impression(data){}
function api_click_hit(id_campaign,id_partner){var url_api_click=URL_API_AT+"api/click_hit";return $.ajax({url:url_api_click,data:"id_campaign="+ id_campaign+"&id_partner="+ id_partner,type:"GET",dataType:"jsonp",crossDomain:true,jsonp:"click",jsonpCallback:"jsonp_call_result_click"});}
function api_miss_hit(id_campaign,id_partner){var url_api_click=URL_API_AT+"api/miss_hit";return $.ajax({url:url_api_click,data:"id_campaign="+ id_campaign+"&id_partner="+ id_partner,type:"GET",dataType:"jsonp",crossDomain:true,jsonp:"miss",jsonpCallback:"jsonp_call_result_miss"});}
function call_tracker_3rd(url){$.getJSON(url+'&callback=?');}
function call_tracker_impression(aid){url_tracker_impression="http://www.hayhaytv.vn/user/tracking_delivery&aid="+aid;$.getJSON(url_tracker_impression+'&callback=?');}
function jsonp_call_result_click(data){}
function jsonp_call_result_miss(data){}
function advertiseProcessEvent(advertise,eventAdvertise)
{var idAdvertise=advertise.find('.idAdvertise').val();var page=advertise.find('.pageNameAdvertise').val();var label=advertise.find('.labelAdvertise').val();var name=advertise.find('.nameAdvertise').val();var value=label+' '+ name;if(parseInt(idAdvertise)){ga_event(page,eventAdvertise,value);if(idAdvertise==16){advertise.find('a').prop('title','danh ba web bacdau.vn');advertise.find('img').prop('alt','danh ba web bacdau.vn');}
var tracker_view=advertise.find('.tracker_viewAdvertise').val();var tracker_click=advertise.find('.trackerAdvertise').val();if(tracker_view&&eventAdvertise=='View'){call_tracker_3rd(tracker_view);}
if(tracker_click&&eventAdvertise=='Click'){call_tracker_3rd(tracker_click);}
var at_campaign_id=advertise.find('.atCampaignIdAdvertise').val();var at_partner_id=advertise.find('.atPartnerIdAdvertise').val();if(at_campaign_id&&at_partner_id){if(eventAdvertise=='View'){api_impression_hit(at_campaign_id,at_partner_id);}
else{api_click_hit(at_campaign_id,at_partner_id);}}
var daily_impression=advertise.find('.daily_impressionAdvertise').val();if(daily_impression){call_tracker_impression(idAdvertise);}}}
$(document).ready(function(){$(".AdvertiseBanner").each(function(index,value){var advertise=$(value);advertiseProcessEvent(advertise,'View');});$(".AdvertiseBanner").mousedown(function(e){var advertise=$(this);advertiseProcessEvent(advertise,'Click');});});